# Generated by Django 5.2.15 on 2026-06-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('enrollment_id', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('ENQUIRY', 'Enquiry'), ('APPLIED', 'Admission Applied'), ('VERIFIED', 'Verified'), ('ENROLLED', 'Enrolled'), ('ACADEMIC', 'Academic Monitoring'), ('JOB', 'Job Assistance'), ('COMPLETED', 'Completed')], default='ENQUIRY', max_length=20)),
            ],
        ),
    ]
