# Generated by Django 5.2.15 on 2026-06-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='status',
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
