# Generated by Django 5.2.15 on 2026-06-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_beneficiary_status_beneficiary_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='status',
            field=models.CharField(choices=[('ENQUIRY', 'Enquiry'), ('APPLIED', 'Admission Applied'), ('VERIFIED', 'Verified'), ('ENROLLED', 'Enrolled'), ('ACADEMIC', 'Academic Monitoring'), ('JOB', 'Job Assistance'), ('COMPLETED', 'Completed')], default='ENQUIRY', max_length=20),
        ),
    ]
