# Generated by Django 5.2.15 on 2026-06-17 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_beneficiary_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=200)),
                ('course_name', models.CharField(max_length=200)),
                ('academic_year', models.CharField(max_length=50)),
                ('application_date', models.DateField()),
                ('support_required', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('beneficiary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.beneficiary')),
            ],
        ),
    ]
