# Generated by Django 5.2.15 on 2026-06-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_admissionapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='family_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
