# Generated by Django 5.2.15 on 2026-06-24 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_admissionapplication_family_income_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('cgpa', models.FloatField()),
                ('attendance', models.FloatField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.beneficiary')),
            ],
        ),
    ]
