# Generated by Django 5.2.15 on 2026-06-24 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_academicrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_disbursed', models.FloatField()),
                ('purpose', models.CharField(max_length=200)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('disbursement_date', models.DateField(auto_now_add=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.beneficiary')),
            ],
        ),
    ]
