# Generated by Django 6.0.6 on 2026-07-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_dynamicfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='applicant_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
