# Generated by Django 6.0.6 on 2026-07-12 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_beneficiary_applicant_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiaryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='beneficiary_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.beneficiary')),
            ],
        ),
    ]
