# Generated by Django 6.0.6 on 2026-07-12 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_beneficiarydocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('VERIFY', 'Application Verified'), ('ENROLL', 'Beneficiary Enrolled'), ('EDIT', 'Profile Edited'), ('DOC_UPLOAD', 'Document Uploaded'), ('DOC_DELETE', 'Document Deleted')], max_length=20)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('beneficiary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='accounts.beneficiary')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
