# Generated by Django 6.0.6 on 2026-07-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='status',
            field=models.CharField(choices=[('ENQUIRY', 'Enquiry'), ('APPLIED', 'Admission Applied'), ('VERIFIED', 'Verified'), ('ENROLLED', 'Enrolled'), ('JOB', 'Job Assistance'), ('COMPLETED', 'Completed')], default='ENQUIRY', max_length=20),
        ),
    ]
