# Generated by Django 6.0.6 on 2026-07-13 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_beneficiary_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('VERIFY', 'Application Verified'), ('ENROLL', 'Beneficiary Enrolled'), ('EDIT', 'Profile Edited'), ('DOC_UPLOAD', 'Document Uploaded'), ('DOC_DELETE', 'Document Deleted'), ('FUNDING', 'Funding Entry Added')], max_length=20),
        ),
        migrations.CreateModel(
            name='FundingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_entries', to='accounts.beneficiary')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
