# Generated by Django 6.0.6 on 2026-07-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_adminaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='bank_account_holder_relation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='bank_branch_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='bank_ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='bank_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
