# Generated by Django 6.0.6 on 2026-07-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_admissionapplication_bank_account_holder_relation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='performed_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
